import Pokemon from './pokemon'

test('1) Create a new object pokemon', () => {
  const myPokemon = new Pokemon('Pikachu')
  expect(myPokemon.name).toBe('Pikachu'); // Corrige esta prueba
<<<<<<< HEAD
	//DESCARGA LAS DEPENDENCIAS DENTRO DE ESTE DIRECTORIO USANDO npm install
	//ESE COMANDO VA A DESCARGAR TODAS LAS DEPENDENCIAS NECESARIAS
	//PARA CORRER EL TEST ES NECESARIO TENER LAS DEPENDENCIAS Y SE CORRE LAS PRUEBAS USANDO npm test
=======
  //DESCARGA LAS DEPENDENCIAS DENTRO DE ESTE DIRECTORIO USANDO npm install
	//ESE COMANDO VA A DESCARGAR TODAS LAS DEPENDENCIAS NECESARIAS
	//PARA CORRER EL TEST ES NECESARIO TENER LAS DEPENDENCIAS Y SE CORRE LAS PRUEBAS USANDO npm test

  
>>>>>>> 346cff20e6ce7c20b79e5da1ffed690c4c829a9f
});
